### ISSUE TITLE
Taiwan is not a country, it also uses the Chinese flag

### ISSUE THREAD

**Issue by jiaohxiong** [gavin-lb/vue3-flag-icons#1]

**Comment by gavin-lb** [comment]
This library uses country codes defined in [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) published by the [International Organization for Standardization](https://en.wikipedia.org/wiki/International_Organization_for_Standardization). For desputes regarding country codes and sovereignty, please take it up with the International Organization for Standardization.
